namespace Restaurant.Modelos{
    public class Tab_Cliente{
        public int Id_Cliente { get; set; }
        public string Ced_Rif { get; set; }
        public string Nom_Cliente { get; set; }
        public string Dir_Cliente { get; set; }
        public string Tel1_Cliente { get; set; }
        public string Tel2_Cliente { get; set; }
        public string Tel3_Cliente { get; set; }
        public string Email_Cliente { get; set; }

         }
   }